"""add_logistics_rate_card_tables

Revision ID: 9dd21f7889b9
Revises: convert_serialization_uuid
Create Date: 2026-01-15 10:26:48.552648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dd21f7889b9'
down_revision: Union[str, None] = 'convert_serialization_uuid'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
