from app.models.user import User, UserRole
from app.models.role import Role, RoleLevel
from app.models.permission import Permission, RolePermission
from app.models.module import Module
from app.models.region import Region, RegionType
from app.models.audit_log import AuditLog
from app.models.category import Category
from app.models.brand import Brand
from app.models.product import (
    Product,
    ProductStatus,
    ProductItemType,
    ProductImage,
    ProductSpecification,
    ProductVariant,
    ProductDocument,
    DocumentType,
)
from app.models.customer import (
    Customer,
    CustomerAddress,
    CustomerType,
    CustomerSource,
    AddressType,
)
from app.models.order import (
    Order,
    OrderItem,
    OrderStatus,
    OrderStatusHistory,
    Payment,
    PaymentStatus,
    PaymentMethod,
    OrderSource,
    Invoice,
)
from app.models.warehouse import Warehouse, WarehouseType
from app.models.inventory import (
    StockItem,
    StockItemStatus,
    InventorySummary,
    StockMovement,
    StockMovementType,
)
from app.models.stock_transfer import (
    StockTransfer,
    StockTransferItem,
    StockTransferSerial,
    TransferStatus,
    TransferType,
)
from app.models.stock_adjustment import (
    StockAdjustment,
    StockAdjustmentItem,
    AdjustmentType,
    AdjustmentStatus,
    InventoryAudit,
)
from app.models.technician import (
    Technician,
    TechnicianStatus,
    TechnicianType,
    SkillLevel,
    TechnicianJobHistory,
    TechnicianLeave,
)
from app.models.service_request import (
    ServiceRequest,
    ServiceType,
    ServicePriority,
    ServiceStatus,
    ServiceSource,
    ServiceStatusHistory,
    PartsRequest,
)
from app.models.amc import (
    AMCContract,
    AMCType,
    AMCStatus,
    AMCPlan,
)
from app.models.installation import (
    Installation,
    InstallationStatus,
    WarrantyClaim,
)
# OMS/WMS Models
from app.models.transporter import (
    Transporter,
    TransporterType,
    TransporterServiceability,
)
# Serviceability & Allocation
from app.models.serviceability import (
    WarehouseServiceability,
    AllocationRule,
    AllocationLog,
    AllocationType,
    AllocationPriority,
    ChannelCode,
)
from app.models.wms import (
    WarehouseZone,
    WarehouseBin,
    PutAwayRule,
    ZoneType,
    BinType,
)
from app.models.picklist import (
    Picklist,
    PicklistItem,
    PicklistStatus,
    PicklistType,
)
from app.models.manifest import (
    Manifest,
    ManifestItem,
    ManifestStatus,
    BusinessType,
)
from app.models.shipment import (
    Shipment,
    ShipmentTracking,
    ShipmentStatus,
    PaymentMode,
    PackagingType,
)
# Multi-Channel Commerce
from app.models.channel import (
    SalesChannel,
    ChannelType,
    ChannelStatus,
    ChannelPricing,
    ChannelInventory,
    ChannelOrder,
)
# Accounting & Finance
from app.models.accounting import (
    ChartOfAccount,
    AccountType,
    AccountSubType,
    FinancialPeriod,
    FinancialPeriodStatus as PeriodStatus,
    CostCenter,
    JournalEntry,
    JournalEntryLine,
    JournalEntryStatus as JournalStatus,
    GeneralLedger,
    TaxConfiguration,
)
# Enhanced Billing (E-Invoice)
from app.models.billing import (
    TaxInvoice,
    InvoiceItem,
    InvoiceType,
    InvoiceStatus,
    CreditDebitNote,
    CreditDebitNoteItem,
    DocumentType as NoteDocumentType,
    NoteReason,
    EWayBill,
    EWayBillItem,
    EWayBillStatus,
    PaymentReceipt,
    PaymentMode as BillingPaymentMode,
    InvoiceNumberSequence,
)
# Document Sequence (PR/PO/GRN numbering)
from app.models.document_sequence import (
    DocumentSequence,
    DocumentSequenceAudit,
    DocumentType as DocumentSequenceType,
)
# TDS (Tax Deducted at Source)
from app.models.tds import (
    TDSDeduction,
    TDSRate,
    Form16ACertificate,
    TDSSection,
    TDSDeductionStatus,
)
# Dealer/Distributor
from app.models.dealer import (
    Dealer,
    DealerType,
    DealerStatus,
    DealerTier,
    CreditStatus,
    DealerPricing,
    DealerTierPricing,
    DealerCreditLedger,
    TransactionType as DealerTransactionType,
    DealerTarget,
    DealerScheme,
    SchemeType,
    DealerSchemeApplication,
)
# Commission & Incentives
from app.models.commission import (
    CommissionPlan,
    CommissionType,
    CalculationBasis,
    CommissionCategoryRate,
    CommissionProductRate,
    CommissionEarner,
    CommissionTransaction,
    CommissionStatus,
    CommissionPayout,
    CommissionPayoutLine,
    PayoutStatus,
    AffiliateReferral,
)
# Unified Promotions & Channel Commissions
from app.models.promotion import (
    Promotion,
    PromotionType,
    PromotionScope,
    DiscountApplication,
    PromotionStatus,
    PromotionUsage,
    ChannelCommissionPlan,
    ChannelCommissionCategoryRate,
    ChannelCommissionEarning,
    CommissionBeneficiary,
    LoyaltyProgram,
    ReferralProgram,
    CustomerReferral,
)
# Vendor/Supplier (Procure-to-Pay)
from app.models.vendor import (
    Vendor,
    VendorType,
    VendorStatus,
    VendorGrade,
    PaymentTerms,
    VendorLedger,
    VendorTransactionType,
    VendorContact,
)
# Purchase/Procurement
from app.models.purchase import (
    PurchaseRequisition,
    PurchaseRequisitionItem,
    RequisitionStatus,
    PurchaseOrder,
    PurchaseOrderItem,
    POStatus,
    PODeliverySchedule,
    DeliveryLotStatus,
    GoodsReceiptNote,
    GRNItem,
    GRNStatus,
    QualityCheckResult,
    VendorInvoice,
    VendorInvoiceStatus,
    VendorProformaInvoice,
    VendorProformaItem,
    ProformaStatus,
    # Sales Return Notes
    SalesReturnNote,
    SRNItem,
    SRNStatus,
    ReturnReason,
    ItemCondition,
    RestockDecision,
    PickupStatus,
    ResolutionType,
)
# Company/Business Entity
from app.models.company import (
    Company,
    CompanyType,
    GSTRegistrationType,
    CompanyBranch,
    CompanyBankAccount,
)
# Call Center CRM
from app.models.call_center import (
    Call,
    CallDisposition,
    CallbackSchedule,
    CallQAReview,
    CallType,
    CallCategory,
    CallStatus,
    CallOutcome,
    CustomerSentiment,
    CallPriority,
    CallbackStatus,
    QAStatus,
)
# Lead Management
from app.models.lead import (
    Lead,
    LeadActivity,
    LeadScoreRule,
    LeadAssignmentRule,
    LeadSource,
    LeadStatus,
    LeadPriority,
    LeadType,
    LeadInterest,
    ActivityType,
    LostReason,
)
# Escalation Management
from app.models.escalation import (
    EscalationMatrix,
    Escalation,
    EscalationHistory,
    EscalationComment,
    EscalationNotification,
    SLAConfiguration,
    EscalationLevel,
    EscalationStatus,
    EscalationPriority,
    EscalationSource,
    EscalationReason,
    NotificationChannel,
)
# Notifications
from app.models.notifications import (
    Notification,
    NotificationPreference,
    NotificationTemplate,
    Announcement,
    AnnouncementDismissal,
    NotificationType,
    NotificationPriority,
)
# Campaign Management
from app.models.campaign import (
    CampaignTemplate,
    AudienceSegment,
    Campaign,
    CampaignRecipient,
    CampaignAutomation,
    CampaignAutomationLog,
    UnsubscribeList,
    CampaignType,
    CampaignStatus,
    CampaignCategory,
    AudienceType,
    DeliveryStatus,
)
# Franchisee CRM
from app.models.franchisee import (
    Franchisee,
    FranchiseeContract,
    FranchiseeTerritory,
    FranchiseeServiceability,
    FranchiseePerformance,
    FranchiseeTraining,
    FranchiseeSupport,
    FranchiseeSupportComment,
    FranchiseeAudit,
    FranchiseeStatus,
    FranchiseeType,
    FranchiseeTier,
    ContractStatus,
    TerritoryStatus,
    TrainingStatus,
    TrainingType,
    SupportTicketStatus,
    SupportTicketPriority,
    SupportTicketCategory,
    AuditStatus,
    AuditType,
    AuditResult,
    ServiceCapability,
)
# Serialization (Barcode Generation)
from app.models.serialization import (
    SerialSequence,
    POSerial,
    ModelCodeReference,
    SupplierCode,
    SerialStatus,
    ItemType,
)
# Multi-Level Approval Workflow
from app.models.approval import (
    ApprovalRequest,
    ApprovalHistory,
    ApprovalEntityType,
    ApprovalLevel,
    ApprovalStatus,
    get_approval_level,
    get_approval_level_name,
)
# HR & Payroll
from app.models.hr import (
    Department,
    Employee,
    SalaryStructure,
    Attendance,
    LeaveBalance,
    LeaveRequest,
    Payroll,
    Payslip,
    EmploymentType,
    EmployeeStatus,
    LeaveType,
    LeaveStatus,
    AttendanceStatus,
    PayrollStatus,
    Gender,
    MaritalStatus,
)
# Rate Cards (Logistics Pricing)
from app.models.rate_card import (
    D2CRateCard,
    D2CWeightSlab,
    D2CSurcharge,
    ZoneMapping,
    B2BRateCard,
    B2BRateSlab,
    B2BAdditionalCharge,
    FTLRateCard,
    FTLLaneRate,
    FTLAdditionalCharge,
    FTLVehicleType,
    CarrierPerformance,
    ServiceType,
    ZoneCode,
    SurchargeType,
    CalculationType,
    B2BServiceType,
    TransportMode,
    B2BRateType,
    FTLRateType,
    VehicleCategory,
)
# S&OP (Sales and Operations Planning)
from app.models.snop import (
    DemandForecast,
    ForecastAdjustment,
    SupplyPlan,
    SNOPScenario,
    ExternalFactor,
    InventoryOptimization,
    SNOPMeeting,
    ForecastGranularity,
    ForecastLevel,
    ForecastStatus,
    ForecastAlgorithm,
    SupplyPlanStatus,
    ScenarioStatus,
    ExternalFactorType,
)
# Abandoned Cart
from app.models.abandoned_cart import (
    AbandonedCart,
    CartRecoveryEmail,
    CartStatus,
    RecoveryChannel,
    RecoveryStatus,
)
# Wishlist
from app.models.wishlist import WishlistItem
# Product Reviews & Q&A
from app.models.product_review import (
    ProductReview,
    ReviewHelpful,
    ProductQuestion,
    ProductAnswer,
    QuestionHelpful,
    AnswerHelpful,
)
# Return Orders & Refunds
from app.models.return_order import (
    ReturnOrder,
    ReturnItem,
    ReturnStatusHistory,
    Refund,
)
# Product Cost (COGS Auto-calculation)
from app.models.product_cost import (
    ProductCost,
    ValuationMethod,
)
# CMS (D2C Content Management)
from app.models.cms import (
    CMSBanner,
    CMSUsp,
    CMSTestimonial,
    CMSAnnouncement,
    CMSPage,
    CMSPageVersion,
    CMSSeo,
    CMSPageStatus,
    CMSAnnouncementType,
    CMSFeatureBar,
    CMSMegaMenuItem,
    CMSMegaMenuItemType,
    DemoBooking,
    DemoBookingStatus,
    VideoGuide,
    VideoGuideCategory,
)
# Community Sales Channel (Meesho-style)
from app.models.community_partner import (
    CommunityPartner,
    PartnerTier,
    PartnerCommission,
    PartnerPayout,
    PartnerReferral,
    PartnerTraining,
    PartnerOrder,
    PartnerStatus,
    KYCStatus,
    CommissionStatus as PartnerCommissionStatus,
    PayoutStatus as PartnerPayoutStatus,
    PayoutMethod,
)
# DOM (Distributed Order Management)
from app.models.dom import (
    FulfillmentNode,
    FulfillmentNodeType,
    RoutingRule,
    RoutingStrategy,
    OrderSplit,
    SplitReason,
    OrchestrationLog,
    OrchestrationStatus,
    Backorder,
    BackorderStatus,
    Preorder,
    PreorderStatus,
    GlobalInventoryView,
)
# Advanced WMS (Wave Picking, Task Interleaving, Slot Optimization)
from app.models.wms_advanced import (
    PickWave,
    WavePicklist,
    WarehouseTask,
    SlotScore,
    CrossDock,
    WorkerLocation,
    WaveType,
    WaveStatus,
    TaskType,
    TaskStatus,
    TaskPriority,
    SlotClass,
    CrossDockType,
    CrossDockStatus,
)
# Omnichannel (BOPIS/BORIS/Ship-from-Store)
from app.models.omnichannel import (
    StoreLocation,
    BOPISOrder,
    ShipFromStoreOrder,
    StoreInventoryReservation,
    StoreReturn,
    StoreType,
    StoreStatus,
    BOPISStatus,
    ShipFromStoreStatus,
    StoreReturnStatus,
    InventoryReservationType,
    PickupLocationType,
)

__all__ = [
    # Access Control
    "User",
    "UserRole",
    "Role",
    "RoleLevel",
    "Permission",
    "RolePermission",
    "Module",
    "Region",
    "RegionType",
    "AuditLog",
    # Products
    "Category",
    "Brand",
    "Product",
    "ProductStatus",
    "ProductItemType",
    "ProductImage",
    "ProductSpecification",
    "ProductVariant",
    "ProductDocument",
    "DocumentType",
    # Customers
    "Customer",
    "CustomerAddress",
    "CustomerType",
    "CustomerSource",
    "AddressType",
    # Orders
    "Order",
    "OrderItem",
    "OrderStatus",
    "OrderStatusHistory",
    "Payment",
    "PaymentStatus",
    "PaymentMethod",
    "OrderSource",
    "Invoice",
    # Inventory
    "Warehouse",
    "WarehouseType",
    "StockItem",
    "StockItemStatus",
    "InventorySummary",
    "StockMovement",
    "StockMovementType",
    "StockTransfer",
    "StockTransferItem",
    "StockTransferSerial",
    "TransferStatus",
    "TransferType",
    "StockAdjustment",
    "StockAdjustmentItem",
    "AdjustmentType",
    "AdjustmentStatus",
    "InventoryAudit",
    # Service
    "Technician",
    "TechnicianStatus",
    "TechnicianType",
    "SkillLevel",
    "TechnicianJobHistory",
    "TechnicianLeave",
    "ServiceRequest",
    "ServiceType",
    "ServicePriority",
    "ServiceStatus",
    "ServiceSource",
    "ServiceStatusHistory",
    "PartsRequest",
    "AMCContract",
    "AMCType",
    "AMCStatus",
    "AMCPlan",
    "Installation",
    "InstallationStatus",
    "WarrantyClaim",
    # OMS/WMS - Transporter
    "Transporter",
    "TransporterType",
    "TransporterServiceability",
    # OMS/WMS - Serviceability & Allocation
    "WarehouseServiceability",
    "AllocationRule",
    "AllocationLog",
    "AllocationType",
    "AllocationPriority",
    "ChannelCode",
    # OMS/WMS - Warehouse Management
    "WarehouseZone",
    "WarehouseBin",
    "PutAwayRule",
    "ZoneType",
    "BinType",
    # OMS/WMS - Picklist
    "Picklist",
    "PicklistItem",
    "PicklistStatus",
    "PicklistType",
    # OMS/WMS - Manifest
    "Manifest",
    "ManifestItem",
    "ManifestStatus",
    "BusinessType",
    # OMS/WMS - Shipment
    "Shipment",
    "ShipmentTracking",
    "ShipmentStatus",
    "PaymentMode",
    "PackagingType",
    # Multi-Channel Commerce
    "SalesChannel",
    "ChannelType",
    "ChannelStatus",
    "ChannelPricing",
    "ChannelInventory",
    "ChannelOrder",
    # Accounting & Finance
    "ChartOfAccount",
    "AccountType",
    "AccountSubType",
    "FinancialPeriod",
    "PeriodStatus",
    "CostCenter",
    "JournalEntry",
    "JournalEntryLine",
    "JournalStatus",
    "GeneralLedger",
    "TaxConfiguration",
    # Enhanced Billing (E-Invoice)
    "TaxInvoice",
    "InvoiceItem",
    "InvoiceType",
    "InvoiceStatus",
    "CreditDebitNote",
    "CreditDebitNoteItem",
    "NoteDocumentType",
    "NoteReason",
    "EWayBill",
    "EWayBillItem",
    "EWayBillStatus",
    "PaymentReceipt",
    "BillingPaymentMode",
    "InvoiceNumberSequence",
    # Document Sequence (PR/PO/GRN)
    "DocumentSequence",
    "DocumentSequenceAudit",
    "DocumentSequenceType",
    # TDS (Tax Deducted at Source)
    "TDSDeduction",
    "TDSRate",
    "Form16ACertificate",
    "TDSSection",
    "TDSDeductionStatus",
    # Dealer/Distributor
    "Dealer",
    "DealerType",
    "DealerStatus",
    "DealerTier",
    "CreditStatus",
    "DealerPricing",
    "DealerTierPricing",
    "DealerCreditLedger",
    "DealerTransactionType",
    "DealerTarget",
    "DealerScheme",
    "SchemeType",
    "DealerSchemeApplication",
    # Commission & Incentives
    "CommissionPlan",
    "CommissionType",
    "CalculationBasis",
    "CommissionCategoryRate",
    "CommissionProductRate",
    "CommissionEarner",
    "CommissionTransaction",
    "CommissionStatus",
    "CommissionPayout",
    "CommissionPayoutLine",
    "PayoutStatus",
    "AffiliateReferral",
    # Unified Promotions & Channel Commissions
    "Promotion",
    "PromotionType",
    "PromotionScope",
    "DiscountApplication",
    "PromotionStatus",
    "PromotionUsage",
    "ChannelCommissionPlan",
    "ChannelCommissionCategoryRate",
    "ChannelCommissionEarning",
    "CommissionBeneficiary",
    "LoyaltyProgram",
    "ReferralProgram",
    "CustomerReferral",
    # Vendor/Supplier (Procure-to-Pay)
    "Vendor",
    "VendorType",
    "VendorStatus",
    "VendorGrade",
    "PaymentTerms",
    "VendorLedger",
    "VendorTransactionType",
    "VendorContact",
    # Purchase/Procurement
    "PurchaseRequisition",
    "PurchaseRequisitionItem",
    "RequisitionStatus",
    "PurchaseOrder",
    "PurchaseOrderItem",
    "POStatus",
    "GoodsReceiptNote",
    "GRNItem",
    "GRNStatus",
    "QualityCheckResult",
    "VendorInvoice",
    "VendorInvoiceStatus",
    "VendorProformaInvoice",
    "VendorProformaItem",
    "ProformaStatus",
    # Company/Business Entity
    "Company",
    "CompanyType",
    "GSTRegistrationType",
    "CompanyBranch",
    "CompanyBankAccount",
    # Call Center CRM
    "Call",
    "CallDisposition",
    "CallbackSchedule",
    "CallQAReview",
    "CallType",
    "CallCategory",
    "CallStatus",
    "CallOutcome",
    "CustomerSentiment",
    "CallPriority",
    "CallbackStatus",
    "QAStatus",
    # Lead Management
    "Lead",
    "LeadActivity",
    "LeadScoreRule",
    "LeadAssignmentRule",
    "LeadSource",
    "LeadStatus",
    "LeadPriority",
    "LeadType",
    "LeadInterest",
    "ActivityType",
    "LostReason",
    # Escalation Management
    "EscalationMatrix",
    "Escalation",
    "EscalationHistory",
    "EscalationComment",
    "EscalationNotification",
    "SLAConfiguration",
    "EscalationLevel",
    "EscalationStatus",
    "EscalationPriority",
    "EscalationSource",
    "EscalationReason",
    "NotificationChannel",
    # Notifications
    "Notification",
    "NotificationPreference",
    "NotificationTemplate",
    "Announcement",
    "AnnouncementDismissal",
    "NotificationType",
    "NotificationPriority",
    # Franchisee CRM
    "Franchisee",
    "FranchiseeContract",
    "FranchiseeTerritory",
    "FranchiseeServiceability",
    "FranchiseePerformance",
    "FranchiseeTraining",
    "FranchiseeSupport",
    "FranchiseeSupportComment",
    "FranchiseeAudit",
    "FranchiseeStatus",
    "FranchiseeType",
    "FranchiseeTier",
    "ContractStatus",
    "TerritoryStatus",
    "TrainingStatus",
    "TrainingType",
    "SupportTicketStatus",
    "SupportTicketPriority",
    "SupportTicketCategory",
    "AuditStatus",
    "AuditType",
    "AuditResult",
    "ServiceCapability",
    # Serialization (Barcode Generation)
    "SerialSequence",
    "POSerial",
    "ModelCodeReference",
    "SupplierCode",
    "SerialStatus",
    "ItemType",
    # Multi-Level Approval Workflow
    "ApprovalRequest",
    "ApprovalHistory",
    "ApprovalEntityType",
    "ApprovalLevel",
    "ApprovalStatus",
    "get_approval_level",
    "get_approval_level_name",
    # HR & Payroll
    "Department",
    "Employee",
    "SalaryStructure",
    "Attendance",
    "LeaveBalance",
    "LeaveRequest",
    "Payroll",
    "Payslip",
    "EmploymentType",
    "EmployeeStatus",
    "LeaveType",
    "LeaveStatus",
    "AttendanceStatus",
    "PayrollStatus",
    "Gender",
    "MaritalStatus",
    # Rate Cards (Logistics Pricing)
    "D2CRateCard",
    "D2CWeightSlab",
    "D2CSurcharge",
    "ZoneMapping",
    "B2BRateCard",
    "B2BRateSlab",
    "B2BAdditionalCharge",
    "FTLRateCard",
    "FTLLaneRate",
    "FTLAdditionalCharge",
    "FTLVehicleType",
    "CarrierPerformance",
    "ServiceType",
    "ZoneCode",
    "SurchargeType",
    "CalculationType",
    "B2BServiceType",
    "TransportMode",
    "B2BRateType",
    "FTLRateType",
    "VehicleCategory",
    # S&OP (Sales and Operations Planning)
    "DemandForecast",
    "ForecastAdjustment",
    "SupplyPlan",
    "SNOPScenario",
    "ExternalFactor",
    "InventoryOptimization",
    "SNOPMeeting",
    "ForecastGranularity",
    "ForecastLevel",
    "ForecastStatus",
    "ForecastAlgorithm",
    "SupplyPlanStatus",
    "ScenarioStatus",
    "ExternalFactorType",
    # Abandoned Cart
    "AbandonedCart",
    "CartRecoveryEmail",
    "CartStatus",
    "RecoveryChannel",
    "RecoveryStatus",
    # Wishlist
    "WishlistItem",
    # Product Reviews & Q&A
    "ProductReview",
    "ReviewHelpful",
    "ProductQuestion",
    "ProductAnswer",
    "QuestionHelpful",
    "AnswerHelpful",
    # Return Orders & Refunds
    "ReturnOrder",
    "ReturnItem",
    "ReturnStatusHistory",
    "Refund",
    # Product Cost (COGS Auto-calculation)
    "ProductCost",
    "ValuationMethod",
    # CMS (D2C Content Management)
    "CMSBanner",
    "CMSUsp",
    "CMSTestimonial",
    "CMSAnnouncement",
    "CMSPage",
    "CMSPageVersion",
    "CMSSeo",
    "CMSPageStatus",
    "CMSAnnouncementType",
    # Community Sales Channel (Meesho-style)
    "CommunityPartner",
    "PartnerTier",
    "PartnerCommission",
    "PartnerPayout",
    "PartnerReferral",
    "PartnerTraining",
    "PartnerOrder",
    "PartnerStatus",
    "KYCStatus",
    "PartnerCommissionStatus",
    "PartnerPayoutStatus",
    "PayoutMethod",
    # DOM (Distributed Order Management)
    "FulfillmentNode",
    "FulfillmentNodeType",
    "RoutingRule",
    "RoutingStrategy",
    "OrderSplit",
    "SplitReason",
    "OrchestrationLog",
    "OrchestrationStatus",
    "Backorder",
    "BackorderStatus",
    "Preorder",
    "PreorderStatus",
    "GlobalInventoryView",
    # Advanced WMS (Wave Picking, Task Interleaving, Slot Optimization)
    "PickWave",
    "WavePicklist",
    "WarehouseTask",
    "SlotScore",
    "CrossDock",
    "WorkerLocation",
    "WaveType",
    "WaveStatus",
    "TaskType",
    "TaskStatus",
    "TaskPriority",
    "SlotClass",
    "CrossDockType",
    "CrossDockStatus",
    # Omnichannel (BOPIS/BORIS/Ship-from-Store)
    "StoreLocation",
    "BOPISOrder",
    "ShipFromStoreOrder",
    "StoreInventoryReservation",
    "StoreReturn",
    "StoreType",
    "StoreStatus",
    "BOPISStatus",
    "ShipFromStoreStatus",
    "StoreReturnStatus",
    "InventoryReservationType",
    "PickupLocationType",
]
